server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com # eureka 服务端实例名字
  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false # 自己就是注册中心，职责就是维护服务实例，不需要去检索服务、
    # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # 集群版
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版

  #server:
    #enable-self-preservation: false #不启用默认的保护机制，
    #eviction-interval-timer-in-ms: 2000  #设置默认世间为2秒 ，后剔除
spring:
  application:
    name: eureka
