server:
  port: 9001
spring:
  application:
    name: goods
  datasource:
    driver‐class‐name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/zhongrui_goods?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:7001/eureka
    instance:
      prefer‐ip‐address: true
feign:
  hystrix:
    enabled: true
#hystrix 配置
#mybatis:
  #configuration:
    #map-underscore-to-camel-case: true
  #mapper-locations: classpath:mapper/*Mapper.xml
  #type-aliases-package: com.zhongrui.goods.pojo
