server:
  port: 18086

spring:
  thymeleaf:
    cache: false
  application:
    name: search-web
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service‐url:
      defaultZone: http://127.0.0.1:7001/eureka

feign:
  hystrix:
    enabled: true
