server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1 #eureka服务端实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eureka/  #集群
      defaultZone: http://127.0.0.1:${server.port}/eureka/
spring:
  application:
    name: eureka